name: Build & Deploy

on:
  push:
    branches: [ 'master' ]

jobs:
  docker:
    name: Build and push docker
    runs-on: ubuntu-latest
    env:
      SECRET: ${{ secrets.PKG_USER }}
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: login to DockerHub
        if: env.SECRET != 0
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASS }}
      - name: build and push
        uses: docker/build-push-action@v4
        with:
          build-args:
            tag: edge
          context: .
          push: ${{ env.SECRET != 0 }}
          platforms: linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64
          tags: swarmpit/install:edge
